### ISSUE TITLE
No flags are fetched

### ISSUE THREAD

**Issue by orafaaraujo** [launchdarkly/ld-intellij#4]
Hello

I installed the plugin following all steps described at https://docs.launchdarkly.com/integrations/intellij
but no flags are fetched.
I always have 

```
java.lang.NullPointerException
	at com.launchdarkly.intellij.LaunchDarklyApiClient$Companion.projectInstance(LaunchDarklyApiClient.kt:42)
	at com.launchdarkly.intellij.settings.LaunchDarklyApplicationConfigurable.getProjects(LaunchDarklyApplicationSettings.kt:259)
	at com.launchdarkly.intellij.settings.LaunchDarklyApplicationConfigurable.isModified(LaunchDarklyApplicationSettings.kt:178)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.isModified(ConfigurableWrapper.java:177)
```

I'm using:
Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: ide.instant.shutdown=false, external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: com.github.intheclouddan.intellijpluginld, com.phraseapp.androidstudio, name.kropp.intellij.makefile, Docker, wu.seal.tool.jsontokotlin, PythonCore, org.moe.community, com.thoughtworks.gauge, org.jetbrains.kotlin, com.developerphil.adbidea, com.jetbrains.kmm, com.nvinayshetty.DTOnator, com.suusan2go.kotlin-fill-class, siosio.kodkod, ru.adelf.idea.dotenv, org.intellij.plugins.markdown

Any clue?

Thank  you

**Comment by InTheCloudDan** [comment]
Hi @orafaaraujo, I just pushed an internal build of this that should fix that error. If you're on the Beta channel we'll be looking to push it there early next week and will notify you as soon as we do.

**Comment by orafaaraujo** [comment]
Hello, @InTheCloudDan 

Passing to confirm that it's all good in version 0.3.7.

Thanks for that and have a nice day!
